<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LayananSeeder extends Seeder
{
    public function run(): void
    {
        $layanan = [
            // ─── HAIR ───────────────────────────────────────────────────
            [
                'nama_layanan' => 'Hair Cut & Style',
                'kategori'     => 'hair',
                'deskripsi'    => 'Potong rambut profesional dengan konsultasi gaya terkini. Termasuk blow dry dan styling sesuai bentuk wajah.',
                'durasi_menit' => 60,
                'harga'        => 150000,
                'gambar'       => 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 12,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Hair Coloring',
                'kategori'     => 'hair',
                'deskripsi'    => 'Pewarnaan rambut premium dengan produk internasional. Konsultasi warna gratis untuk hasil yang sempurna.',
                'durasi_menit' => 150,
                'harga'        => 450000,
                'gambar'       => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 6,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Hair Spa & Mask',
                'kategori'     => 'hair',
                'deskripsi'    => 'Perawatan rambut intensif dengan masker premium dan pijat kepala relaksasi. Cocok untuk rambut rusak & kering.',
                'durasi_menit' => 90,
                'harga'        => 220000,
                'gambar'       => 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 10,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Smoothing',
                'kategori'     => 'hair',
                'deskripsi'    => 'Pelurusan rambut dengan teknologi terkini. Rambut lebih lembut, halus, dan tahan lama hingga 6 bulan.',
                'durasi_menit' => 180,
                'harga'        => 650000,
                'gambar'       => 'https://images.unsplash.com/photo-1582095133179-bfd08e2fb6b8?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 4,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Keratin Treatment',
                'kategori'     => 'hair',
                'deskripsi'    => 'Treatment keratin premium untuk rambut lebih berkilau, anti-frizz, dan mudah diatur. Hasil tahan 3–5 bulan.',
                'durasi_menit' => 180,
                'harga'        => 800000,
                'gambar'       => 'https://images.unsplash.com/photo-1607006483224-a0e8cc7ec48a?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 3,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Scalp Treatment',
                'kategori'     => 'hair',
                'deskripsi'    => 'Perawatan kulit kepala mendalam untuk mengatasi ketombe, rambut rontok, dan kulit kepala berminyak.',
                'durasi_menit' => 75,
                'harga'        => 280000,
                'gambar'       => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 8,
                'created_at'   => now(), 'updated_at' => now(),
            ],

            // ─── NAIL ───────────────────────────────────────────────────
            [
                'nama_layanan' => 'Manicure Classic',
                'kategori'     => 'nail',
                'deskripsi'    => 'Perawatan kuku tangan lengkap: shaping, cuticle care, buffing, dan polish dengan pilihan warna eksklusif.',
                'durasi_menit' => 60,
                'harga'        => 120000,
                'gambar'       => 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 10,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Pedicure Spa',
                'kategori'     => 'nail',
                'deskripsi'    => 'Perawatan kuku kaki mewah dengan foot soak aromaterapi, scrub gula, dan massage betis yang menenangkan.',
                'durasi_menit' => 75,
                'harga'        => 150000,
                'gambar'       => 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 10,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Nail Art Premium',
                'kategori'     => 'nail',
                'deskripsi'    => 'Desain kuku artistik custom dengan gel polish, glitter, sticker, dan hand-painted art. Eksklusif & tahan lama.',
                'durasi_menit' => 90,
                'harga'        => 200000,
                'gambar'       => 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 8,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Gel Nails Extension',
                'kategori'     => 'nail',
                'deskripsi'    => 'Perpanjangan kuku dengan gel premium. Tampil elegan dengan kuku panjang alami dan tahan hingga 3 minggu.',
                'durasi_menit' => 120,
                'harga'        => 320000,
                'gambar'       => 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 6,
                'created_at'   => now(), 'updated_at' => now(),
            ],

            // ─── FACE & BEAUTY ──────────────────────────────────────────
            [
                'nama_layanan' => 'Deep Cleansing Facial',
                'kategori'     => 'face',
                'deskripsi'    => 'Pembersihan wajah mendalam dengan teknologi ultrasonic dan serum premium untuk kulit bersih bercahaya.',
                'durasi_menit' => 75,
                'harga'        => 280000,
                'gambar'       => 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 8,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Anti-Aging Facial',
                'kategori'     => 'face',
                'deskripsi'    => 'Perawatan anti-penuaan dengan collagen serum, micro-current, dan masker LED. Kulit lebih kencang dan muda.',
                'durasi_menit' => 90,
                'harga'        => 450000,
                'gambar'       => 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 6,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Eyelash Extension',
                'kategori'     => 'face',
                'deskripsi'    => 'Pemasangan bulu mata extension natural yang sempurna. Mata terlihat lebih besar dan ekspresif tanpa riasan.',
                'durasi_menit' => 120,
                'harga'        => 350000,
                'gambar'       => 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 6,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Brow Shaping & Styling',
                'kategori'     => 'face',
                'deskripsi'    => 'Pembentukan alis presisi sesuai bentuk wajah. Termasuk waxing, threading, dan pengisian dengan tinta premium.',
                'durasi_menit' => 45,
                'harga'        => 130000,
                'gambar'       => 'https://images.unsplash.com/photo-1521747116042-5a810fda9664?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 12,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Bridal Makeup',
                'kategori'     => 'face',
                'deskripsi'    => 'Riasan pengantin profesional yang tahan lama. Termasuk konsultasi, trial, dan touch-up kit di hari H.',
                'durasi_menit' => 180,
                'harga'        => 1200000,
                'gambar'       => 'https://images.unsplash.com/photo-1487412947147-5cebf100d281?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 2,
                'created_at'   => now(), 'updated_at' => now(),
            ],

            // ─── RELAXATION ─────────────────────────────────────────────
            [
                'nama_layanan' => 'Full Body Massage',
                'kategori'     => 'relaxation',
                'deskripsi'    => 'Pijat tubuh penuh dengan teknik Swedish dan deep tissue. Hilangkan lelah dan ketegangan otot secara menyeluruh.',
                'durasi_menit' => 90,
                'harga'        => 320000,
                'gambar'       => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 8,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Aromatherapy Spa',
                'kategori'     => 'relaxation',
                'deskripsi'    => 'Ritual spa aromaterapi dengan essential oil pilihan dan musik relaksasi. Pengalaman spa mewah yang memanjakan.',
                'durasi_menit' => 120,
                'harga'        => 480000,
                'gambar'       => 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 6,
                'created_at'   => now(), 'updated_at' => now(),
            ],
            [
                'nama_layanan' => 'Hot Stone Therapy',
                'kategori'     => 'relaxation',
                'deskripsi'    => 'Terapi batu panas vulkanik yang merilekskan otot dan meningkatkan sirkulasi darah. Sensasi spa bintang 5.',
                'durasi_menit' => 90,
                'harga'        => 420000,
                'gambar'       => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80',
                'status'       => 'available',
                'kuota_harian' => 6,
                'created_at'   => now(), 'updated_at' => now(),
            ],
        ];

        DB::table('layanan')->insert($layanan);
    }
}
